[packages]
fisher = [
  'davidtwco/hydro'
]

[packages.darwin]
brews = [  
  'cmake',
  'fd',
  'fish',
  'git',
  'git-absorb',
  'helix',
  'hyperfine',
  'jj',
  'jq',
  'ninja',
  'qemu',
  'ripgrep',
  'rustup',
  'sk',
  'typst',
  'zellij'
]
casks = [
  '1password-cli',
  'alacritty'
]

[packages.fedora]
copr = [
  'varlad/zellij'
]
packages = [
  'cmake',
  'fd-find',
  'fish',
  'git',
  'git-absorb',
  'helix',
  'hyperfine',
  'jq',
  'ninja-build',
  'ripgrep',
  'rustup',
  'skim',
  'zellij'
]

[packages.ubuntu]
packages = [
  'cmake',
  'fd-find',
  'fish',
  'git',
  'git-absorb',
  'hyperfine',
  'jq',
  'ninja-build',
  'ripgrep',
  'rustup',
]
